version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: proyecto_tsic2
      MYSQL_USER: root
      MYSQL_PASSWORD: Mysql123
      MYSQL_ROOT_PASSWORD: Mysql123
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
  app:
    build:
      args:
        user: victor
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:88
    networks:
      - laravel
networks:
  laravel: